# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: destroyed-symlinks
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
  - repo: https://github.com/golangci/golangci-lint/
    rev: v1.51.2
    hooks:
      - id: golangci-lint
