// Code generated by wsdl2go. DO NOT EDIT.

package sledzeniehttpbinding

import (
	"github.com/fiorix/wsdl2go/soap"
)

// Namespace was auto-generated from WSDL.
var Namespace = "http://sledzenie.pocztapolska.pl"

// NewSledzeniePortType creates an initializes a SledzeniePortType.
func NewSledzeniePortType(cli *soap.Client) SledzeniePortType {
	return &sledzeniePortType{cli}
}

// SledzeniePortType was auto-generated from WSDL
// and defines interface for the remote service. Useful for testing.
type SledzeniePortType interface {
	// MaksymalnaLiczbaPrzesylek was auto-generated from WSDL.
	MaksymalnaLiczbaPrzesylek() (*MaksymalnaLiczbaPrzesylekResponse, error)

	// SprawdzPrzesylke was auto-generated from WSDL.
	SprawdzPrzesylke(SprawdzPrzesylke *SprawdzPrzesylke) (*SprawdzPrzesylkeResponse, error)

	// SprawdzPrzesylkePl was auto-generated from WSDL.
	SprawdzPrzesylkePl(SprawdzPrzesylkePl *SprawdzPrzesylkePl) (*SprawdzPrzesylkePlResponse, error)

	// SprawdzPrzesylki was auto-generated from WSDL.
	SprawdzPrzesylki(SprawdzPrzesylki *SprawdzPrzesylki) (*SprawdzPrzesylkiResponse, error)

	// SprawdzPrzesylkiOdDo was auto-generated from WSDL.
	SprawdzPrzesylkiOdDo(SprawdzPrzesylkiOdDo *SprawdzPrzesylkiOdDo) (*SprawdzPrzesylkiOdDoResponse, error)

	// SprawdzPrzesylkiOdDoPl was auto-generated from WSDL.
	SprawdzPrzesylkiOdDoPl(SprawdzPrzesylkiOdDoPl *SprawdzPrzesylkiOdDoPl) (*SprawdzPrzesylkiOdDoPlResponse, error)

	// SprawdzPrzesylkiPl was auto-generated from WSDL.
	SprawdzPrzesylkiPl(SprawdzPrzesylkiPl *SprawdzPrzesylkiPl) (*SprawdzPrzesylkiPlResponse, error)

	// Wersja was auto-generated from WSDL.
	Wersja() (*WersjaResponse, error)

	// Witaj was auto-generated from WSDL.
	Witaj(Witaj *Witaj) (*WitajResponse, error)
}

// Date in WSDL format.
type Date string

// DanePrzesylki was auto-generated from WSDL.
type DanePrzesylki struct {
	DataNadania       *Date         `xml:"dataNadania,omitempty" json:"dataNadania,omitempty" yaml:"dataNadania,omitempty"`
	Format            *string       `xml:"format,omitempty" json:"format,omitempty" yaml:"format,omitempty"`
	KodKrajuNadania   *string       `xml:"kodKrajuNadania,omitempty" json:"kodKrajuNadania,omitempty" yaml:"kodKrajuNadania,omitempty"`
	KodKrajuPrzezn    *string       `xml:"kodKrajuPrzezn,omitempty" json:"kodKrajuPrzezn,omitempty" yaml:"kodKrajuPrzezn,omitempty"`
	KodRodzPrzes      *string       `xml:"kodRodzPrzes,omitempty" json:"kodRodzPrzes,omitempty" yaml:"kodRodzPrzes,omitempty"`
	KrajNadania       *string       `xml:"krajNadania,omitempty" json:"krajNadania,omitempty" yaml:"krajNadania,omitempty"`
	KrajPrzezn        *string       `xml:"krajPrzezn,omitempty" json:"krajPrzezn,omitempty" yaml:"krajPrzezn,omitempty"`
	Masa              *float64      `xml:"masa,omitempty" json:"masa,omitempty" yaml:"masa,omitempty"`
	Numer             *string       `xml:"numer,omitempty" json:"numer,omitempty" yaml:"numer,omitempty"`
	ProceduraSerwis   *Procedura    `xml:"proceduraSerwis,omitempty" json:"proceduraSerwis,omitempty" yaml:"proceduraSerwis,omitempty"`
	RodzPrzes         *string       `xml:"rodzPrzes,omitempty" json:"rodzPrzes,omitempty" yaml:"rodzPrzes,omitempty"`
	UrzadNadania      *Jednostka    `xml:"urzadNadania,omitempty" json:"urzadNadania,omitempty" yaml:"urzadNadania,omitempty"`
	UrzadPrzezn       *Jednostka    `xml:"urzadPrzezn,omitempty" json:"urzadPrzezn,omitempty" yaml:"urzadPrzezn,omitempty"`
	ZakonczonoObsluge *bool         `xml:"zakonczonoObsluge,omitempty" json:"zakonczonoObsluge,omitempty" yaml:"zakonczonoObsluge,omitempty"`
	Zdarzenia         *ListaZdarzen `xml:"zdarzenia,omitempty" json:"zdarzenia,omitempty" yaml:"zdarzenia,omitempty"`
}

// GodzinyPracy was auto-generated from WSDL.
type GodzinyPracy struct {
	DniRobocze *GodzinyZUwagami `xml:"dniRobocze,omitempty" json:"dniRobocze,omitempty" yaml:"dniRobocze,omitempty"`
	NiedzISw   *GodzinyZUwagami `xml:"niedzISw,omitempty" json:"niedzISw,omitempty" yaml:"niedzISw,omitempty"`
	Soboty     *GodzinyZUwagami `xml:"soboty,omitempty" json:"soboty,omitempty" yaml:"soboty,omitempty"`
}

// GodzinyZUwagami was auto-generated from WSDL.
type GodzinyZUwagami struct {
	Godziny *string `xml:"godziny,omitempty" json:"godziny,omitempty" yaml:"godziny,omitempty"`
	Uwagi   *string `xml:"uwagi,omitempty" json:"uwagi,omitempty" yaml:"uwagi,omitempty"`
}

// Jednostka was auto-generated from WSDL.
type Jednostka struct {
	DaneSzczegolowe *SzczDaneJednostki `xml:"daneSzczegolowe,omitempty" json:"daneSzczegolowe,omitempty" yaml:"daneSzczegolowe,omitempty"`
	Nazwa           *string            `xml:"nazwa,omitempty" json:"nazwa,omitempty" yaml:"nazwa,omitempty"`
}

// Komunikat was auto-generated from WSDL.
type Komunikat struct {
	Przesylki *ListaPrzesylek `xml:"przesylki,omitempty" json:"przesylki,omitempty" yaml:"przesylki,omitempty"`
	Status    *int            `xml:"status,omitempty" json:"status,omitempty" yaml:"status,omitempty"`
}

// ListaPrzesylek was auto-generated from WSDL.
type ListaPrzesylek struct {
	Przesylka []*Przesylka `xml:"przesylka,omitempty" json:"przesylka,omitempty" yaml:"przesylka,omitempty"`
}

// ListaPrzesylekPowiazanych was auto-generated from WSDL.
type ListaPrzesylekPowiazanych struct {
	PrzesylkaPowiazana []*PrzesylkaPowiazana `xml:"przesylkaPowiazana,omitempty" json:"przesylkaPowiazana,omitempty" yaml:"przesylkaPowiazana,omitempty"`
}

// ListaZdarzen was auto-generated from WSDL.
type ListaZdarzen struct {
	Zdarzenie []*Zdarzenie `xml:"zdarzenie,omitempty" json:"zdarzenie,omitempty" yaml:"zdarzenie,omitempty"`
}

// Procedura was auto-generated from WSDL.
type Procedura struct {
	Kod                *string                    `xml:"kod,omitempty" json:"kod,omitempty" yaml:"kod,omitempty"`
	KopertaFirmowa     *string                    `xml:"kopertaFirmowa,omitempty" json:"kopertaFirmowa,omitempty" yaml:"kopertaFirmowa,omitempty"`
	Nazwa              *string                    `xml:"nazwa,omitempty" json:"nazwa,omitempty" yaml:"nazwa,omitempty"`
	PrzesylkiPowiazane *ListaPrzesylekPowiazanych `xml:"przesylkiPowiazane,omitempty" json:"przesylkiPowiazane,omitempty" yaml:"przesylkiPowiazane,omitempty"`
}

// Przesylka was auto-generated from WSDL.
type Przesylka struct {
	DanePrzesylki *DanePrzesylki `xml:"danePrzesylki,omitempty" json:"danePrzesylki,omitempty" yaml:"danePrzesylki,omitempty"`
	Numer         *string        `xml:"numer,omitempty" json:"numer,omitempty" yaml:"numer,omitempty"`
	Status        *int           `xml:"status,omitempty" json:"status,omitempty" yaml:"status,omitempty"`
}

// PrzesylkaPowiazana was auto-generated from WSDL.
type PrzesylkaPowiazana struct {
	NrPrzesylkiPowiazanej *string `xml:"nrPrzesylkiPowiazanej,omitempty" json:"nrPrzesylkiPowiazanej,omitempty" yaml:"nrPrzesylkiPowiazanej,omitempty"`
}

// Przyczyna was auto-generated from WSDL.
type Przyczyna struct {
	Kod   *string `xml:"kod,omitempty" json:"kod,omitempty" yaml:"kod,omitempty"`
	Nazwa *string `xml:"nazwa,omitempty" json:"nazwa,omitempty" yaml:"nazwa,omitempty"`
}

// SzczDaneJednostki was auto-generated from WSDL.
type SzczDaneJednostki struct {
	DlGeogr      *float64      `xml:"dlGeogr,omitempty" json:"dlGeogr,omitempty" yaml:"dlGeogr,omitempty"`
	GodzinyPracy *GodzinyPracy `xml:"godzinyPracy,omitempty" json:"godzinyPracy,omitempty" yaml:"godzinyPracy,omitempty"`
	Miejscowosc  *string       `xml:"miejscowosc,omitempty" json:"miejscowosc,omitempty" yaml:"miejscowosc,omitempty"`
	NrDomu       *string       `xml:"nrDomu,omitempty" json:"nrDomu,omitempty" yaml:"nrDomu,omitempty"`
	NrLokalu     *string       `xml:"nrLokalu,omitempty" json:"nrLokalu,omitempty" yaml:"nrLokalu,omitempty"`
	Pna          *string       `xml:"pna,omitempty" json:"pna,omitempty" yaml:"pna,omitempty"`
	SzerGeogr    *float64      `xml:"szerGeogr,omitempty" json:"szerGeogr,omitempty" yaml:"szerGeogr,omitempty"`
	Ulica        *string       `xml:"ulica,omitempty" json:"ulica,omitempty" yaml:"ulica,omitempty"`
}

// Zdarzenie was auto-generated from WSDL.
type Zdarzenie struct {
	Czas      *string    `xml:"czas,omitempty" json:"czas,omitempty" yaml:"czas,omitempty"`
	Jednostka *Jednostka `xml:"jednostka,omitempty" json:"jednostka,omitempty" yaml:"jednostka,omitempty"`
	Kod       *string    `xml:"kod,omitempty" json:"kod,omitempty" yaml:"kod,omitempty"`
	Konczace  *bool      `xml:"konczace,omitempty" json:"konczace,omitempty" yaml:"konczace,omitempty"`
	Nazwa     *string    `xml:"nazwa,omitempty" json:"nazwa,omitempty" yaml:"nazwa,omitempty"`
	Przyczyna *Przyczyna `xml:"przyczyna,omitempty" json:"przyczyna,omitempty" yaml:"przyczyna,omitempty"`
}

// MaksymalnaLiczbaPrzesylekResponse was auto-generated from WSDL.
type MaksymalnaLiczbaPrzesylekResponse struct {
	Return *int `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SprawdzPrzesylke was auto-generated from WSDL.
type SprawdzPrzesylke struct {
	Numer *string `xml:"numer,omitempty" json:"numer,omitempty" yaml:"numer,omitempty"`
}

// SprawdzPrzesylkePl was auto-generated from WSDL.
type SprawdzPrzesylkePl struct {
	Numer *string `xml:"numer,omitempty" json:"numer,omitempty" yaml:"numer,omitempty"`
}

// SprawdzPrzesylkePlResponse was auto-generated from WSDL.
type SprawdzPrzesylkePlResponse struct {
	Return *Przesylka `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SprawdzPrzesylkeResponse was auto-generated from WSDL.
type SprawdzPrzesylkeResponse struct {
	Return *Przesylka `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SprawdzPrzesylki was auto-generated from WSDL.
type SprawdzPrzesylki struct {
	Numer []*string `xml:"numer,omitempty" json:"numer,omitempty" yaml:"numer,omitempty"`
}

// SprawdzPrzesylkiOdDo was auto-generated from WSDL.
type SprawdzPrzesylkiOdDo struct {
	Numer  []*string `xml:"numer,omitempty" json:"numer,omitempty" yaml:"numer,omitempty"`
	OdDnia *string   `xml:"odDnia,omitempty" json:"odDnia,omitempty" yaml:"odDnia,omitempty"`
	DoDnia *string   `xml:"doDnia,omitempty" json:"doDnia,omitempty" yaml:"doDnia,omitempty"`
}

// SprawdzPrzesylkiOdDoPl was auto-generated from WSDL.
type SprawdzPrzesylkiOdDoPl struct {
	Numer  []*string `xml:"numer,omitempty" json:"numer,omitempty" yaml:"numer,omitempty"`
	OdDnia *string   `xml:"odDnia,omitempty" json:"odDnia,omitempty" yaml:"odDnia,omitempty"`
	DoDnia *string   `xml:"doDnia,omitempty" json:"doDnia,omitempty" yaml:"doDnia,omitempty"`
}

// SprawdzPrzesylkiOdDoPlResponse was auto-generated from WSDL.
type SprawdzPrzesylkiOdDoPlResponse struct {
	Return *Komunikat `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SprawdzPrzesylkiOdDoResponse was auto-generated from WSDL.
type SprawdzPrzesylkiOdDoResponse struct {
	Return *Komunikat `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SprawdzPrzesylkiPl was auto-generated from WSDL.
type SprawdzPrzesylkiPl struct {
	Numer []*string `xml:"numer,omitempty" json:"numer,omitempty" yaml:"numer,omitempty"`
}

// SprawdzPrzesylkiPlResponse was auto-generated from WSDL.
type SprawdzPrzesylkiPlResponse struct {
	Return *Komunikat `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SprawdzPrzesylkiResponse was auto-generated from WSDL.
type SprawdzPrzesylkiResponse struct {
	Return *Komunikat `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// WersjaResponse was auto-generated from WSDL.
type WersjaResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// Witaj was auto-generated from WSDL.
type Witaj struct {
	Imie *string `xml:"imie,omitempty" json:"imie,omitempty" yaml:"imie,omitempty"`
}

// WitajResponse was auto-generated from WSDL.
type WitajResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// Operation wrapper for MaksymalnaLiczbaPrzesylek.
// OperationMaksymalnaLiczbaPrzesylekResponse was auto-generated
// from WSDL.
type OperationMaksymalnaLiczbaPrzesylekResponse struct {
	MaksymalnaLiczbaPrzesylekResponse *MaksymalnaLiczbaPrzesylekResponse `xml:"maksymalnaLiczbaPrzesylekResponse,omitempty" json:"maksymalnaLiczbaPrzesylekResponse,omitempty" yaml:"maksymalnaLiczbaPrzesylekResponse,omitempty"`
}

// Operation wrapper for SprawdzPrzesylke.
// OperationSprawdzPrzesylkeRequest was auto-generated from WSDL.
type OperationSprawdzPrzesylkeRequest struct {
	SprawdzPrzesylke *SprawdzPrzesylke `xml:"sprawdzPrzesylke,omitempty" json:"sprawdzPrzesylke,omitempty" yaml:"sprawdzPrzesylke,omitempty"`
}

// Operation wrapper for SprawdzPrzesylke.
// OperationSprawdzPrzesylkeResponse was auto-generated from WSDL.
type OperationSprawdzPrzesylkeResponse struct {
	SprawdzPrzesylkeResponse *SprawdzPrzesylkeResponse `xml:"sprawdzPrzesylkeResponse,omitempty" json:"sprawdzPrzesylkeResponse,omitempty" yaml:"sprawdzPrzesylkeResponse,omitempty"`
}

// Operation wrapper for SprawdzPrzesylkePl.
// OperationSprawdzPrzesylkePlRequest was auto-generated from WSDL.
type OperationSprawdzPrzesylkePlRequest struct {
	SprawdzPrzesylkePl *SprawdzPrzesylkePl `xml:"sprawdzPrzesylkePl,omitempty" json:"sprawdzPrzesylkePl,omitempty" yaml:"sprawdzPrzesylkePl,omitempty"`
}

// Operation wrapper for SprawdzPrzesylkePl.
// OperationSprawdzPrzesylkePlResponse was auto-generated from
// WSDL.
type OperationSprawdzPrzesylkePlResponse struct {
	SprawdzPrzesylkePlResponse *SprawdzPrzesylkePlResponse `xml:"sprawdzPrzesylkePlResponse,omitempty" json:"sprawdzPrzesylkePlResponse,omitempty" yaml:"sprawdzPrzesylkePlResponse,omitempty"`
}

// Operation wrapper for SprawdzPrzesylki.
// OperationSprawdzPrzesylkiRequest was auto-generated from WSDL.
type OperationSprawdzPrzesylkiRequest struct {
	SprawdzPrzesylki *SprawdzPrzesylki `xml:"sprawdzPrzesylki,omitempty" json:"sprawdzPrzesylki,omitempty" yaml:"sprawdzPrzesylki,omitempty"`
}

// Operation wrapper for SprawdzPrzesylki.
// OperationSprawdzPrzesylkiResponse was auto-generated from WSDL.
type OperationSprawdzPrzesylkiResponse struct {
	SprawdzPrzesylkiResponse *SprawdzPrzesylkiResponse `xml:"sprawdzPrzesylkiResponse,omitempty" json:"sprawdzPrzesylkiResponse,omitempty" yaml:"sprawdzPrzesylkiResponse,omitempty"`
}

// Operation wrapper for SprawdzPrzesylkiOdDo.
// OperationSprawdzPrzesylkiOdDoRequest was auto-generated from
// WSDL.
type OperationSprawdzPrzesylkiOdDoRequest struct {
	SprawdzPrzesylkiOdDo *SprawdzPrzesylkiOdDo `xml:"sprawdzPrzesylkiOdDo,omitempty" json:"sprawdzPrzesylkiOdDo,omitempty" yaml:"sprawdzPrzesylkiOdDo,omitempty"`
}

// Operation wrapper for SprawdzPrzesylkiOdDo.
// OperationSprawdzPrzesylkiOdDoResponse was auto-generated from
// WSDL.
type OperationSprawdzPrzesylkiOdDoResponse struct {
	SprawdzPrzesylkiOdDoResponse *SprawdzPrzesylkiOdDoResponse `xml:"sprawdzPrzesylkiOdDoResponse,omitempty" json:"sprawdzPrzesylkiOdDoResponse,omitempty" yaml:"sprawdzPrzesylkiOdDoResponse,omitempty"`
}

// Operation wrapper for SprawdzPrzesylkiOdDoPl.
// OperationSprawdzPrzesylkiOdDoPlRequest was auto-generated from
// WSDL.
type OperationSprawdzPrzesylkiOdDoPlRequest struct {
	SprawdzPrzesylkiOdDoPl *SprawdzPrzesylkiOdDoPl `xml:"sprawdzPrzesylkiOdDoPl,omitempty" json:"sprawdzPrzesylkiOdDoPl,omitempty" yaml:"sprawdzPrzesylkiOdDoPl,omitempty"`
}

// Operation wrapper for SprawdzPrzesylkiOdDoPl.
// OperationSprawdzPrzesylkiOdDoPlResponse was auto-generated from
// WSDL.
type OperationSprawdzPrzesylkiOdDoPlResponse struct {
	SprawdzPrzesylkiOdDoPlResponse *SprawdzPrzesylkiOdDoPlResponse `xml:"sprawdzPrzesylkiOdDoPlResponse,omitempty" json:"sprawdzPrzesylkiOdDoPlResponse,omitempty" yaml:"sprawdzPrzesylkiOdDoPlResponse,omitempty"`
}

// Operation wrapper for SprawdzPrzesylkiPl.
// OperationSprawdzPrzesylkiPlRequest was auto-generated from WSDL.
type OperationSprawdzPrzesylkiPlRequest struct {
	SprawdzPrzesylkiPl *SprawdzPrzesylkiPl `xml:"sprawdzPrzesylkiPl,omitempty" json:"sprawdzPrzesylkiPl,omitempty" yaml:"sprawdzPrzesylkiPl,omitempty"`
}

// Operation wrapper for SprawdzPrzesylkiPl.
// OperationSprawdzPrzesylkiPlResponse was auto-generated from
// WSDL.
type OperationSprawdzPrzesylkiPlResponse struct {
	SprawdzPrzesylkiPlResponse *SprawdzPrzesylkiPlResponse `xml:"sprawdzPrzesylkiPlResponse,omitempty" json:"sprawdzPrzesylkiPlResponse,omitempty" yaml:"sprawdzPrzesylkiPlResponse,omitempty"`
}

// Operation wrapper for Wersja.
// OperationWersjaResponse was auto-generated from WSDL.
type OperationWersjaResponse struct {
	WersjaResponse *WersjaResponse `xml:"wersjaResponse,omitempty" json:"wersjaResponse,omitempty" yaml:"wersjaResponse,omitempty"`
}

// Operation wrapper for Witaj.
// OperationWitajRequest was auto-generated from WSDL.
type OperationWitajRequest struct {
	Witaj *Witaj `xml:"witaj,omitempty" json:"witaj,omitempty" yaml:"witaj,omitempty"`
}

// Operation wrapper for Witaj.
// OperationWitajResponse was auto-generated from WSDL.
type OperationWitajResponse struct {
	WitajResponse *WitajResponse `xml:"witajResponse,omitempty" json:"witajResponse,omitempty" yaml:"witajResponse,omitempty"`
}

// sledzeniePortType implements the SledzeniePortType interface.
type sledzeniePortType struct {
	cli *soap.Client
}

// MaksymalnaLiczbaPrzesylek was auto-generated from WSDL.
func (p *sledzeniePortType) MaksymalnaLiczbaPrzesylek() (*MaksymalnaLiczbaPrzesylekResponse, error) {
	α := struct {
	}{}

	γ := struct {
		OperationMaksymalnaLiczbaPrzesylekResponse `xml:"maksymalnaLiczbaPrzesylekResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("MaksymalnaLiczbaPrzesylek", α, &γ); err != nil {
		return nil, err
	}
	return γ.MaksymalnaLiczbaPrzesylekResponse, nil
}

// SprawdzPrzesylke was auto-generated from WSDL.
func (p *sledzeniePortType) SprawdzPrzesylke(SprawdzPrzesylke *SprawdzPrzesylke) (*SprawdzPrzesylkeResponse, error) {
	α := struct {
		OperationSprawdzPrzesylkeRequest `xml:"ns:sprawdzPrzesylke"`
	}{
		OperationSprawdzPrzesylkeRequest{
			SprawdzPrzesylke,
		},
	}

	γ := struct {
		OperationSprawdzPrzesylkeResponse `xml:"sprawdzPrzesylkeResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SprawdzPrzesylke", α, &γ); err != nil {
		return nil, err
	}
	return γ.SprawdzPrzesylkeResponse, nil
}

// SprawdzPrzesylkePl was auto-generated from WSDL.
func (p *sledzeniePortType) SprawdzPrzesylkePl(SprawdzPrzesylkePl *SprawdzPrzesylkePl) (*SprawdzPrzesylkePlResponse, error) {
	α := struct {
		OperationSprawdzPrzesylkePlRequest `xml:"ns:sprawdzPrzesylkePl"`
	}{
		OperationSprawdzPrzesylkePlRequest{
			SprawdzPrzesylkePl,
		},
	}

	γ := struct {
		OperationSprawdzPrzesylkePlResponse `xml:"sprawdzPrzesylkePlResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SprawdzPrzesylkePl", α, &γ); err != nil {
		return nil, err
	}
	return γ.SprawdzPrzesylkePlResponse, nil
}

// SprawdzPrzesylki was auto-generated from WSDL.
func (p *sledzeniePortType) SprawdzPrzesylki(SprawdzPrzesylki *SprawdzPrzesylki) (*SprawdzPrzesylkiResponse, error) {
	α := struct {
		OperationSprawdzPrzesylkiRequest `xml:"ns:sprawdzPrzesylki"`
	}{
		OperationSprawdzPrzesylkiRequest{
			SprawdzPrzesylki,
		},
	}

	γ := struct {
		OperationSprawdzPrzesylkiResponse `xml:"sprawdzPrzesylkiResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SprawdzPrzesylki", α, &γ); err != nil {
		return nil, err
	}
	return γ.SprawdzPrzesylkiResponse, nil
}

// SprawdzPrzesylkiOdDo was auto-generated from WSDL.
func (p *sledzeniePortType) SprawdzPrzesylkiOdDo(SprawdzPrzesylkiOdDo *SprawdzPrzesylkiOdDo) (*SprawdzPrzesylkiOdDoResponse, error) {
	α := struct {
		OperationSprawdzPrzesylkiOdDoRequest `xml:"ns:sprawdzPrzesylkiOdDo"`
	}{
		OperationSprawdzPrzesylkiOdDoRequest{
			SprawdzPrzesylkiOdDo,
		},
	}

	γ := struct {
		OperationSprawdzPrzesylkiOdDoResponse `xml:"sprawdzPrzesylkiOdDoResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SprawdzPrzesylkiOdDo", α, &γ); err != nil {
		return nil, err
	}
	return γ.SprawdzPrzesylkiOdDoResponse, nil
}

// SprawdzPrzesylkiOdDoPl was auto-generated from WSDL.
func (p *sledzeniePortType) SprawdzPrzesylkiOdDoPl(SprawdzPrzesylkiOdDoPl *SprawdzPrzesylkiOdDoPl) (*SprawdzPrzesylkiOdDoPlResponse, error) {
	α := struct {
		OperationSprawdzPrzesylkiOdDoPlRequest `xml:"ns:sprawdzPrzesylkiOdDoPl"`
	}{
		OperationSprawdzPrzesylkiOdDoPlRequest{
			SprawdzPrzesylkiOdDoPl,
		},
	}

	γ := struct {
		OperationSprawdzPrzesylkiOdDoPlResponse `xml:"sprawdzPrzesylkiOdDoPlResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SprawdzPrzesylkiOdDoPl", α, &γ); err != nil {
		return nil, err
	}
	return γ.SprawdzPrzesylkiOdDoPlResponse, nil
}

// SprawdzPrzesylkiPl was auto-generated from WSDL.
func (p *sledzeniePortType) SprawdzPrzesylkiPl(SprawdzPrzesylkiPl *SprawdzPrzesylkiPl) (*SprawdzPrzesylkiPlResponse, error) {
	α := struct {
		OperationSprawdzPrzesylkiPlRequest `xml:"ns:sprawdzPrzesylkiPl"`
	}{
		OperationSprawdzPrzesylkiPlRequest{
			SprawdzPrzesylkiPl,
		},
	}

	γ := struct {
		OperationSprawdzPrzesylkiPlResponse `xml:"sprawdzPrzesylkiPlResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SprawdzPrzesylkiPl", α, &γ); err != nil {
		return nil, err
	}
	return γ.SprawdzPrzesylkiPlResponse, nil
}

// Wersja was auto-generated from WSDL.
func (p *sledzeniePortType) Wersja() (*WersjaResponse, error) {
	α := struct {
	}{}

	γ := struct {
		OperationWersjaResponse `xml:"wersjaResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("Wersja", α, &γ); err != nil {
		return nil, err
	}
	return γ.WersjaResponse, nil
}

// Witaj was auto-generated from WSDL.
func (p *sledzeniePortType) Witaj(Witaj *Witaj) (*WitajResponse, error) {
	α := struct {
		OperationWitajRequest `xml:"ns:witaj"`
	}{
		OperationWitajRequest{
			Witaj,
		},
	}

	γ := struct {
		OperationWitajResponse `xml:"witajResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("Witaj", α, &γ); err != nil {
		return nil, err
	}
	return γ.WitajResponse, nil
}
